### ISSUE TITLE
Block the page without consent

### ISSUE THREAD

**Issue by nex2021** [generaxion/cookiebot-accessible-template#2]
Hi, this code was exactly what I was looking for, but I can't figure out how to "block" the page without consent. Otherwise everyone browses bypassing cookies.
In cookiebot it would be the "overlay" model

**Comment by TeemuSuoranta** [comment]
Hi!

I didn't add this by default as it is somewhat unclear at least here in Finland weather blocking page before selection is fine with the local law.

If you do want to block access there are couple of ways:

A) Easy and imperfect way

Add `pointer-events: auto` to `#CookieBannerOverlay` (by default clicking is allowed through it via pointer-events: none) and this alone will prevent clicking in the overlay area. In this case you probably want to also add darker overlay to indicate that the area is unclickable. This is imperfect, though and will let keyboard users / screen readers move past the banner.

B) True blocking

This would require to doing the pointer-events thing from option A and implementing a focus trap like https://github.com/KittyGiraudel/a11y-dialog

You probably cannot use many of these libraries straight out of box as they would want to build their own markup but you could separate focus trapping logic there. It can be somewhat advanced and not recommended unless you are comfortable with JS. I looked into this briefly but stopped when I found out that it is a gray area at least here in Finland.

**Comment by TeemuSuoranta** [comment]
There is now alternative "optimized" template available that is displayed in middle of screen with click blocking overlay.
